### PR TITLE
created knockdown features

### PR DESCRIPTION
**Pull request by ivan-guo**

### CODE REVIEW

**Review by aryang13 — APPROVED** [review]
what a smart cookie you are

**Review by aryang13 — COMMENTED** [review]
there is actually a lot of duplicated code, you could definitely extract and combine the functions into one

**Comment by ivan-guo** [comment]
> there is some duplicated code, you could extract and combine the functions into one, and pass the round numbers in as a variable or extract the large functionality that is the same out

ok fixed now, functions are combined and much cleaner!

**Review by aryang13 — APPROVED** [review]
way cleaner now!

**Comment by ivan-guo** [comment]
Don't merge this yet, I am writing a test for this @straw-hat-gupta

**Pull request merged**
